---
services:

# -- Nodeexporter --------------------------------------------------------------

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    hostname: Zephyros
    restart: unless-stopped
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
    networks:
      - monitoring

  # -- Fritz!Box -------------------------------------------------------------------

  fritz-exporter:
    image: pdreker/fritz_exporter:latest
    container_name: fritz-exporter
    ports:
      - "9787:9787"
    environment:
      - FRITZ_HOSTNAME=${FRITZ_HOSTNAME}
      - FRITZ_USERNAME=${FRITZ_USERNAME}
      - FRITZ_PASSWORD=${FRITZ_PASSWORD}
      - FRITZ_LISTEN_ADDRESS=${FRITZ_LISTEN_ADDRESS}
    restart: unless-stopped
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
