[General]
closeToTray=true
networkCookies="@ByteArray(cc=22tiUT7Ibi6oz4JNOZiLu9JdHP2HcvRVx+LjUsm+DrJr3kwRzNz+fMzwIFx9DDxmdo8=; HttpOnly; expires=Fri, 25-Jun-2027 11:11:22 GMT; domain=localhost; path=/\n)"
startInTray=true
startupDelay=0
windowGeometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\x4\xff\0\0\x2\xb3\0\0\0\0\0\0\0\0\0\0\x4\xff\0\0\x2\xb3\0\0\0\0\0\0\0\0\n\0\0\0\0\0\0\0\0\0\0\0\x4\xff\0\0\x2\xb3)
zoomFactor=1
